private
errorEnded
	self error: 'Round has already ended'